name: Feature Request
description: Suggest something new or different.
labels: ["enhancement"]
body:
  - type: dropdown
    id: plugin
    attributes:
      label: Which plugin?
      options:
        - ActivityFilter
        - SpotifyListenAlong
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe what you want and why it would be useful.
    validations:
      required: true
